#!/bin/bash
#SBATCH --job-name=nn
#SBATCH --output=nn_cu.out
#SBATCH --error=nn_cu.err
#SBATCH --account=mpcs51087
#SBATCH --partition=gpu
#SBATCH --gres=gpu:1
#SBATCH --constraint=v100
#SBATCH --time=00:05:00
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1

srun ./nn_cu